## 1. Contexte et objectif

Consolider, nettoyer et standardiser plusieurs années d’exports Excel hebdomadaires issus d’un cabinet médical afin de constituer un dataset exploitable pour l’analyse.

## 2. Inspection d’un fichier représentatif

In [1]:
import pandas as pd

df_raw = pd.read_excel("compta_2022/2022 Semaine 01.xls")
df_raw.head(20)

,RECETTES JOURNALIERES,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SEMAINE 01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Date,Actes,NaN,Nom du patient,Espèces,Chèque,CB,A.T.,CMU,AME,Tiers Payant,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,C,V,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1,03.01.22,1,NaN,SAINZ,NaN,NaN,27,NaN,NaN,NaN,17.5,NaN
7,2,NaN,1,NaN,CARMASOL,NaN,25,NaN,NaN,NaN,NaN,NaN,NaN
8,3,NaN,1,NaN,MEZIERE,NaN,NaN,27,NaN,NaN,NaN,NaN,NaN
9,4,NaN,1,NaN,GUILOHEL,NaN,NaN,NaN,NaN,NaN,NaN,25,NaN
10,5,NaN,1,NaN,VUILLAMY,NaN,52,NaN,NaN,NaN,NaN,NaN,NaN
11,6,NaN,1,NaN,EL AMCHAOUI,NaN,NaN,NaN,25,NaN,NaN,NaN,NaN
12,7,NaN,1,NaN,BRUNET,NaN,27,NaN,NaN,NaN,NaN,NaN,NaN
13,8,NaN,1,NaN,AICH,NaN,NaN,27,NaN,NaN,NaN,NaN,NaN
14,9,NaN,1,NaN,DESCHAMPS,NaN,NaN,27,NaN,NaN,NaN,NaN,NaN
15,10,04.01.22,3,NaN,BENAZAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,11,NaN,1,NaN,JOUVENCY,NaN,NaN,27,NaN,NaN,NaN,NaN,NaN
17,12,NaN,1,NaN,BERDINELLE,NaN,NaN,25,NaN,NaN,NaN,NaN,NaN
18,13,NaN,1,NaN,ZANA,NaN,NaN,25,NaN,NaN,NaN,NaN,NaN
19,14,NaN,1,NaN,DROMAIN,NaN,NaN,25,NaN,NaN,NaN,NaN,NaN

### Inspection d’un fichier représentatif

Avant de construire le pipeline de nettoyage, une inspection manuelle d’un fichier Excel représentatif a été réalisée afin de comprendre la structure des données.

Plusieurs problèmes apparaissent immédiatement :

- présence de lignes vides ;
- présence de lignes de total non utiles à l’analyse ;
- dates renseignées uniquement au début de chaque bloc de consultations ;
- formats de dates hétérogènes selon les fichiers ;
- colonnes parfois entièrement vides ;
- données numériques importées comme du texte ;
- présence de données nominatives patients.

Ces constats justifient la mise en place d’un pipeline de nettoyage automatisé afin de traiter l’ensemble des fichiers de manière homogène.

### Stratégie de nettoyage

Afin de traiter plusieurs années de données de manière reproductible, une fonction de nettoyage automatisée a été construite.

Les principales étapes du pipeline sont les suivantes :

- suppression des lignes entièrement vides ;
- suppression des lignes de synthèse (totaux) ;
- suppression des lignes sans information patient ;
- propagation des dates sur les lignes d’un même bloc de consultations ;
- harmonisation des formats de dates ;
- conversion des colonnes numériques vers un format exploitable ;
- certaines colonnes présentent de nombreuses valeurs manquantes selon les semaines ;
- anonymisation des patients via génération d’un identifiant unique ;
- fusion de l’ensemble des fichiers nettoyés dans un dataset consolidé.

In [2]:
# Import des bibliothèques
import hashlib
from glob import glob

## 3. Fonction de nettoyage

In [3]:
def nettoyer_fichier(path):
    # lecture brute
    df = pd.read_excel(path, header=None)

    # suppression lignes totalement vides
    df = df.dropna(how='all')

    # suppression colonne compteur
    df = df.drop(columns=df.columns[0])

    # renommage des colonnes
    df.columns = [
        'date',
        'consultations',
        'visites',
        'nom_patient',
        'especes',
        'cheque',
        'cb',
        'at',
        'cmu',
        'ame',
        'tiers_payant',
        'total'
    ]

    # les exports se terminent systématiquement par 3 lignes de total non exploitables
    df = df.iloc[:-3].copy()

    # suppression lignes sans patient
    df = df[
        df['nom_patient'].notna()
        & (df['nom_patient'].str.strip() != 'Nom du patient')
        ]

    # suppression header parasite
    df = df[df['date'] != 'Date'].copy()

    # Conversion des faux vides (chaînes blanches) en valeurs manquantes
    df['date'] = df['date'].replace(r'^\s*$', pd.NA, regex=True)
    
    df['date'] = df['date'].ffill()
    
    df['date'] = df['date'].apply(
        lambda x: (
            str(x).strip().replace(' ', '').replace('/', '-').replace('.', '-')
            if isinstance(x, str)
            else x
        )
    )
    
    df['date'] = pd.to_datetime(
        df['date'],
        format='mixed',
        dayfirst=True,
        errors='coerce'
        )
        
    
    # suppression colonnes inutiles
    df = df.drop(columns=['total'])

    # conversion numérique
    colonnes_num = [
        'consultations',
        'visites',
        'especes',
        'cheque',
        'cb',
        'at',
        'cmu',
        'ame',
        'tiers_payant'
    ]

    df[colonnes_num] = df[colonnes_num].apply(
        pd.to_numeric,
        errors='coerce'
    )

    # suppression lignes sans aucune information utile
    df = df.dropna(subset=colonnes_num, how='all')
    
    # anonymisation des patients
    df['patient_id'] = df['nom_patient'].apply(
        lambda x: hashlib.sha256(str(x).encode()).hexdigest()
    )

    df = df.drop(columns=['nom_patient'])

    # reset index
    df = df.reset_index(drop=True)

    return df

In [4]:
# validation du pipeline sur un fichier représentatif
df_test = nettoyer_fichier("compta_2022/2022 Semaine 03.xls")

In [5]:
df_test.head()

,date,consultations,visites,especes,cheque,cb,at,cmu,ame,tiers_payant,patient_id
0,2022-01-17,1,NaN,NaN,26.0,NaN,NaN,NaN,NaN,NaN,265f64154d34f385f9a71f447d76b44f55c2b333fe9647...
1,2022-01-17,1,NaN,NaN,26.0,NaN,NaN,NaN,NaN,NaN,64ff8dbdfaa235ba3dccc51c335ad9e013e8635b4f8826...
2,2022-01-17,1,NaN,NaN,NaN,27.0,NaN,NaN,NaN,NaN,65aea765a2e9dc6e8cdee5d284817ffae577bb4f7070bf...
3,2022-01-17,1,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,15ea8327a3800f289cd1eafef792b6e308d11b6220da68...
4,2022-01-17,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,d91b5f5de0ae51c08e046dee0ccd1e3c2c6c48a0df99e6...

In [6]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           47 non-null     datetime64[ns]
 1   consultations  47 non-null     int64
 2   visites        0 non-null      float64
 3   especes        2 non-null      float64
 4   cheque         11 non-null     float64
 5   cb             28 non-null     float64
 6   at             0 non-null      float64
 7   cmu            1 non-null      float64
 8   ame            0 non-null      float64
 9   tiers_payant   6 non-null      float64
 10  patient_id     47 non-null     object
dtypes: datetime64[ns](1), float64(8), int64(1), object(1)
memory usage: 4.2+ KB

## 4. Récupération automatique des fichiers Excel

In [7]:
chemins = glob("compta_*/*.xls")

In [8]:
dfs = []

for path in chemins:
    try:
        df = nettoyer_fichier(path)
        dfs.append(df)
        print(f"OK : {path}")
    except Exception as e:
        print(f"ERREUR : {path} -> {e}")

OK : compta_2022\2022 Semaine 01.xls
OK : compta_2022\2022 Semaine 02.xls
OK : compta_2022\2022 Semaine 03.xls
OK : compta_2022\2022 Semaine 04.xls
OK : compta_2022\2022 Semaine 05.xls
OK : compta_2022\2022 Semaine 06.xls
OK : compta_2022\2022 Semaine 07.xls
OK : compta_2022\2022 Semaine 08.xls
OK : compta_2022\2022 Semaine 09.xls
OK : compta_2022\2022 Semaine 10.xls
OK : compta_2022\2022 Semaine 11 .xls
OK : compta_2022\2022 Semaine 12.xls
OK : compta_2022\2022 Semaine 13.xls
OK : compta_2022\2022 Semaine 14.xls
OK : compta_2022\2022 Semaine 15.xls
OK : compta_2022\2022 Semaine 16.xls
OK : compta_2022\2022 Semaine 17.xls
OK : compta_2022\2022 Semaine 18.xls
OK : compta_2022\2022 Semaine 19.xls
OK : compta_2022\2022 Semaine 20.xls
OK : compta_2022\2022 Semaine 21.xls
OK : compta_2022\2022 Semaine 22.xls
OK : compta_2022\2022 Semaine 23.xls
OK : compta_2022\2022 Semaine 24.xls
OK : compta_2022\2022 Semaine 25.xls
OK : compta_2022\2022 Semaine 26.xls
OK : compta_2022\2022 Semaine 27.xls
OK : compta_2022\2022 Semaine 28.xls
OK : compta_2022\2022 Semaine 29.xls
OK : compta_2022\2022 Semaine 30.xls
OK : compta_2022\2022 Semaine 34.xls
OK : compta_2022\2022 Semaine 35.xls
OK : compta_2022\2022 Semaine 36.xls
OK : compta_2022\2022 Semaine 37.xls
OK : compta_2022\2022 Semaine 38.xls
OK : compta_2022\2022 Semaine 39.xls
OK : compta_2022\2022 Semaine 40.xls
OK : compta_2022\2022 Semaine 41.xls
OK : compta_2022\2022 Semaine 42.xls
OK : compta_2022\2022 Semaine 43.xls
OK : compta_2022\2022 Semaine 44.xls
OK : compta_2022\2022 Semaine 45.xls
OK : compta_2022\2022 Semaine 46.xls
OK : compta_2022\2022 Semaine 47.xls
OK : compta_2022\2022 Semaine 48.xls
OK : compta_2022\2022 Semaine 49.xls
OK : compta_2022\2022 Semaine 50.xls
OK : compta_2022\2022 Semaine 51.xls
OK : compta_2022\2022 Semaine 52.xls
OK : compta_2023\2023 Semaine 01.xls
OK : compta_2023\2023 Semaine 02.xls
OK : compta_2023\2023 Semaine 03.xls
OK : compta_2023\2023 Semaine 04.xls
OK : compta_2023\2023 Semaine 05.xls
OK : compta_2023\2023 Semaine 06.xls
OK : compta_2023\2023 Semaine 07.xls
OK : compta_2023\2023 Semaine 08.xls
OK : compta_2023\2023 Semaine 09.xls
OK : compta_2023\2023 Semaine 10.xls
OK : compta_2023\2023 Semaine 11.xls
OK : compta_2023\2023 Semaine 12.xls
OK : compta_2023\2023 Semaine 13.xls
OK : compta_2023\2023 Semaine 14.xls
OK : compta_2023\2023 Semaine 15.xls
OK : compta_2023\2023 Semaine 16.xls
OK : compta_2023\2023 Semaine 17.xls
OK : compta_2023\2023 Semaine 18.xls
OK : compta_2023\2023 Semaine 19.xls
OK : compta_2023\2023 Semaine 20.xls
OK : compta_2023\2023 Semaine 21.xls
OK : compta_2023\2023 Semaine 22.xls
OK : compta_2023\2023 Semaine 23.xls
OK : compta_2023\2023 Semaine 24.xls
OK : compta_2023\2023 Semaine 25.xls
OK : compta_2023\2023 Semaine 26.xls
OK : compta_2023\2023 Semaine 27.xls
OK : compta_2023\2023 Semaine 28.xls
OK : compta_2023\2023 Semaine 29.xls
OK : compta_2023\2023 Semaine 30.xls
OK : compta_2023\2023 Semaine 31.xls
OK : compta_2023\2023 Semaine 32.xls
OK : compta_2023\2023 Semaine 33.xls
OK : compta_2023\2023 Semaine 34.xls
OK : compta_2023\2023 Semaine 35.xls
OK : compta_2023\2023 Semaine 36.xls
OK : compta_2023\2023 Semaine 37.xls
OK : compta_2023\2023 Semaine 38.xls
OK : compta_2023\2023 Semaine 39.xls
OK : compta_2023\2023 Semaine 40.xls
OK : compta_2023\2023 Semaine 41.xls
OK : compta_2023\2023 Semaine 42.xls
OK : compta_2023\2023 Semaine 43.xls
OK : compta_2023\2023 Semaine 44.xls
OK : compta_2023\2023 Semaine 45.xls
OK : compta_2023\2023 Semaine 46.xls
OK : compta_2023\2023 Semaine 47.xls
OK : compta_2023\2023 Semaine 48.xls
OK : compta_2023\2023 Semaine 49.xls
OK : compta_2023\2023 Semaine 50.xls
OK : compta_2023\2023 Semaine 51.xls
OK : compta_2023\2023 Semaine 52.xls
OK : compta_2024\2024 Semaine 01.xls
OK : compta_2024\2024 Semaine 02.xls
OK : compta_2024\2024 Semaine 03.xls
OK : compta_2024\2024 Semaine 04.xls
OK : compta_2024\2024 Semaine 05.xls
OK : compta_2024\2024 Semaine 06.xls
OK : compta_2024\2024 Semaine 07.xls
OK : compta_2024\2024 Semaine 08.xls
OK : compta_2024\2024 Semaine 09.xls
OK : compta_2024\2024 Semaine 10.xls
OK : compta_2024\2024 Semaine 11.xls
OK : compta_2024\2024 Semaine 12.xls
OK : compta_2024\2024 Semaine 13.xls
OK : compta_2024\2024 Semaine 14.xls
OK : compta_2024\2024 Semaine 15.xls
OK : compta_2024\2024 Semaine 16.xls
OK : compta_2024\2024 Semaine 17.xls
OK : compta_2024\2024 Semaine 18.xls
OK : compta_2024\2024 Semaine 19.xls
OK : compta_2024\2024 Semaine 20.xls
OK : compta_2024\2024 Semaine 21.xls
OK : compta_2024\2024 Semaine 22.xls
OK : compta_2024\2024 Semaine 23.xls
OK : compta_2024\2024 Semaine 24.xls
OK : compta_2024\2024 Semaine 25.xls
OK : compta_2024\2024 Semaine 26.xls
OK : compta_2024\2024 Semaine 27.xls
OK : compta_2024\2024 Semaine 28.xls
OK : compta_2024\2024 Semaine 29.xls
OK : compta_2024\2024 Semaine 30.xls
OK : compta_2024\2024 Semaine 31.xls
OK : compta_2024\2024 Semaine 32.xls
OK : compta_2024\2024 Semaine 33.xls
OK : compta_2024\2024 Semaine 34.xls
OK : compta_2024\2024 Semaine 35.xls
OK : compta_2024\2024 Semaine 36.xls
OK : compta_2024\2024 Semaine 37.xls
OK : compta_2024\2024 Semaine 38.xls
OK : compta_2024\2024 Semaine 39.xls
OK : compta_2024\2024 Semaine 40.xls
OK : compta_2024\2024 Semaine 41.xls
OK : compta_2024\2024 Semaine 42.xls
OK : compta_2024\2024 Semaine 43.xls
OK : compta_2024\2024 Semaine 44.xls
OK : compta_2024\2024 Semaine 45.xls
OK : compta_2024\2024 Semaine 46.xls
OK : compta_2024\2024 Semaine 47.xls
OK : compta_2024\2024 Semaine 48.xls
OK : compta_2024\2024 Semaine 49.xls
OK : compta_2024\2024 Semaine 50.xls
OK : compta_2024\2024 Semaine 51.xls
OK : compta_2024\2024 Semaine 52.xls
OK : compta_2025\2025 Semaine 01.xls
OK : compta_2025\2025 Semaine 02.xls
OK : compta_2025\2025 Semaine 03.xls
OK : compta_2025\2025 Semaine 04.xls
OK : compta_2025\2025 Semaine 05.xls
OK : compta_2025\2025 Semaine 06.xls
OK : compta_2025\2025 Semaine 07.xls
OK : compta_2025\2025 Semaine 08.xls
OK : compta_2025\2025 Semaine 09.xls
OK : compta_2025\2025 Semaine 10.xls
OK : compta_2025\2025 Semaine 11.xls
OK : compta_2025\2025 Semaine 12.xls
OK : compta_2025\2025 Semaine 13.xls
OK : compta_2025\2025 Semaine 14.xls
OK : compta_2025\2025 Semaine 15.xls
OK : compta_2025\2025 Semaine 16.xls
OK : compta_2025\2025 Semaine 17.xls
OK : compta_2025\2025 Semaine 18.xls
OK : compta_2025\2025 Semaine 19.xls
OK : compta_2025\2025 Semaine 20.xls
OK : compta_2025\2025 Semaine 21.xls
OK : compta_2025\2025 Semaine 22.xls
OK : compta_2025\2025 Semaine 23.xls
OK : compta_2025\2025 Semaine 24.xls
OK : compta_2025\2025 Semaine 25.xls
OK : compta_2025\2025 Semaine 26.xls
OK : compta_2025\2025 Semaine 27.xls
OK : compta_2025\2025 Semaine 28.xls
OK : compta_2025\2025 Semaine 29.xls
OK : compta_2025\2025 Semaine 30.xls
OK : compta_2025\2025 Semaine 31.xls
OK : compta_2025\2025 Semaine 32.xls
OK : compta_2025\2025 Semaine 33.xls
OK : compta_2025\2025 Semaine 34.xls
OK : compta_2025\2025 Semaine 35.xls
OK : compta_2025\2025 Semaine 36.xls
OK : compta_2025\2025 Semaine 37.xls
OK : compta_2025\2025 Semaine 38.xls
OK : compta_2025\2025 Semaine 39.xls
OK : compta_2025\2025 Semaine 40.xls
OK : compta_2025\2025 Semaine 41.xls
OK : compta_2025\2025 Semaine 42.xls
OK : compta_2025\2025 Semaine 43.xls
OK : compta_2025\2025 Semaine 44.xls
OK : compta_2025\2025 Semaine 45.xls
OK : compta_2025\2025 Semaine 46.xls
OK : compta_2025\2025 Semaine 47.xls
OK : compta_2025\2025 Semaine 48.xls
OK : compta_2025\2025 Semaine 49.xls
OK : compta_2025\2025 Semaine 50.xls
OK : compta_2025\2025 Semaine 51.xls
OK : compta_2025\2025 Semaine 52.xls
OK : compta_2026\2026 Semaine 01.xls
OK : compta_2026\2026 Semaine 02.xls
OK : compta_2026\2026 Semaine 03.xls
OK : compta_2026\2026 Semaine 04.xls
OK : compta_2026\2026 Semaine 05.xls
OK : compta_2026\2026 Semaine 06.xls
OK : compta_2026\2026 Semaine 07.xls
OK : compta_2026\2026 Semaine 08.xls
OK : compta_2026\2026 Semaine 09.xls
OK : compta_2026\2026 Semaine 10.xls
OK : compta_2026\2026 Semaine 11.xls
OK : compta_2026\2026 Semaine 12.xls
OK : compta_2026\2026 Semaine 13.xls
OK : compta_2026\2026 Semaine 14.xls
OK : compta_2026\2026 Semaine 15.xls
OK : compta_2026\2026 Semaine 16.xls
OK : compta_2026\2026 Semaine 17.xls
OK : compta_2026\2026 Semaine 18.xls
OK : compta_2026\2026 Semaine 19.xls
OK : compta_2026\2026 Semaine 20.xls
OK : compta_2026\2026 Semaine 21.xls
OK : compta_2026\2026 Semaine 22.xls
OK : compta_2026\2026 Semaine 23.xls
OK : compta_2026\2026 Semaine 24.xls
OK : compta_2026\2026 Semaine 25.xls
OK : compta_2026\2026 Semaine 26.xls
OK : compta_2026\2026 Semaine 27.xls

## 5. Fusion des fichiers nettoyés

In [9]:
dfs = [
    df for df in dfs
    if not df.empty and not df.isna().all(axis=None)
]

df_global = pd.concat(dfs, ignore_index=True)

In [10]:
df_global.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9001 entries, 0 to 9000
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           9001 non-null   datetime64[ns]
 1   consultations  8930 non-null   float64
 2   visites        43 non-null     float64
 3   especes        552 non-null    float64
 4   cheque         948 non-null    float64
 5   cb             5202 non-null   float64
 6   at             271 non-null    float64
 7   cmu            85 non-null     float64
 8   ame            12 non-null     float64
 9   tiers_payant   2515 non-null   float64
 10  patient_id     9001 non-null   object
dtypes: datetime64[ns](1), float64(9), object(1)
memory usage: 773.7+ KB

## 6. Contrôle qualité et préparation du dataset

In [11]:
df_global.isna().sum()

date                0
consultations      71
visites          8958
especes          8449
cheque           8053
cb               3799
at               8730
cmu              8916
ame              8989
tiers_payant     6486
patient_id          0
dtype: int64

In [12]:
# Contrôle des observations sans consultation ni visite enregistrée
(df_global['consultations'].isna()& df_global['visites'].isna()).sum()

np.int64(40)

### Traitement des actes manquants

Un petit nombre de lignes (40 sur plus de 9000) comportaient une information de paiement mais aucune information d’acte (consultation ou visite), vraisemblablement en raison d’oublis de saisie dans les fichiers sources.

Ces cas ont été imputés à une consultation standard (`1`) selon une hypothèse conservative.

In [13]:
mask = (
    df_global['consultations'].isna()
    & df_global['visites'].isna()
)

df_global.loc[mask, 'consultations'] = 1

In [14]:
# Vérification après imputation
df_global[['consultations', 'visites']].isna().sum()

consultations      31
visites          8958
dtype: int64

In [15]:
# Les absences d'information métier sont interprétées comme des zéros
colonnes_zero = [
    'consultations',
    'visites',
    'especes',
    'cheque',
    'cb',
    'at',
    'cmu',
    'ame',
    'tiers_payant'
]

df_global[colonnes_zero] = df_global[colonnes_zero].fillna(0)

In [16]:
df_global.head()

,date,consultations,visites,especes,cheque,cb,at,cmu,ame,tiers_payant,patient_id
0,2022-01-03,1.0,0.0,0.0,0.0,27.0,0.0,0.0,0.0,17.5,1f102b9f7a1841fe7dcf3a5a4401cb301cf1671aedf985...
1,2022-01-03,1.0,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,4c17b9cfd62328cbe9ae67a348f7f21ffc959b9cb12538...
2,2022-01-03,1.0,0.0,0.0,0.0,27.0,0.0,0.0,0.0,0.0,1a85706333f0bb84b3b72c99287e35a0987eed8f9dfe48...
3,2022-01-03,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,b70db1f726f701f0d34938095a6ec0aceef3126527471d...
4,2022-01-03,1.0,0.0,0.0,52.0,0.0,0.0,0.0,0.0,0.0,b5ec0bb5590543dc89761cb16419f2e3a09d5b0098d261...

In [17]:
# Création d'une colonne recette
df_global['recette'] = (
    df_global['especes']
    + df_global['cheque']
    + df_global['cb']
    + df_global['at']
    + df_global['cmu']
    + df_global['ame']
    + df_global['tiers_payant']
)

In [18]:
df_global.to_csv(
    "cabinet_medical_clean.csv",
    index=False,
    encoding="utf-8-sig"
)

## Limites et points en attente

Certaines anomalies détectées nécessitent une validation métier avant traitement définitif :
- observations avec acte sans recette enregistrée ;
- incohérences potentielles sur certaines dates.